### ISSUE TITLE
Broadcast fails in CircuitPython because move_to_end() is not implemented

### ISSUE THREAD

**Issue by aww** [adafruit/Adafruit_CircuitPython_BLE_BroadcastNet#18]
OrderedDict.move_to_end() is used during .broadcast() but this method of OrderedDIct is not implemented in CircuitPython.

```
code.py output:
This is BroadcastNet Feather Sense sensor: e1ea5705e4b6
Traceback (most recent call last):
  File "code.py", line 30, in <module>
  File "adafruit_ble_broadcastnet.py", line 54, in broadcast
  File "adafruit_ble/__init__.py", line 183, in start_advertising
  File "adafruit_ble_broadcastnet.py", line 188, in __bytes__
AttributeError: 'OrderedDict' object has no attribute 'move_to_end'

Code done running.

Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit Feather Bluefruit Sense with nRF52840```

**Comment by tannewt** [comment]
(see discussion in #16 about fixing this)
